bidnbuy/urls.py
import django.conf.urls.i18n
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import set_language

from .views import homePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include("favourites.urls")),
    path('', homePage, name='home'),
    path('', include("users.urls")),
    path('', include("products.urls")),
    path('accounts/', include('allauth.urls')),
    path('setlang/', set_language, name='set_language'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import path
from django.views.i18n import JavaScriptCatalog
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('products/new/', views.newProduct, name="new-product"),
    path('products/mywishlist/', views.myWishlistPage, name='mywishlist'),
    path('products/myproducts/', views.myProductsPage, name='myproducts'),
    path('products/<pk>/', views.detailPage, name='detail-product'),
	path('products/<pk>/edit', views.editProduct, name='edit-product'),
    path('products/<pk>/delete', views.deleteProduct, name='delete')
]

users/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from . import views

urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('activate-user/<uidb64>/<token>', views.activate_user, name="activate"),
    path('resend-link/', views.get_new_activation_link, name="resend_activation"),
    path('request-reset-password', views.request_reset_password, name="request_new_password"),
    path('reset-password/<uidb64>/<token>', views.reset_password, name="reset_password"),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

products/models.py
import calendar
from datetime import datetime, timedelta, timezone
from itertools import product
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import get_language
from django.utils.translation import gettext as _
from phonenumber_field.modelfields import PhoneNumberField
from places.fields import PlacesField
from users.models import Account


from .utils import date_diff_in_seconds, dhms_from_seconds

conditions = [
            ('1', _('New')),
            ('2', _('Used'))
          ]

currencies = [
            ('1', _('LEI')),
            ('2', _('USD (US$)')),
            ('3', _('EUR (€)')),
            ('4', _('GBP (£)'))
]

class Product(models.Model):
    seller = models.ForeignKey(Account, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    date_posted = models.DateTimeField(verbose_name='Date posted', auto_now_add=True)
    last_updated = models.DateTimeField(verbose_name='Date updated', auto_now=True)
    description = models.CharField(max_length=3000)
    condition = models.CharField(max_length=20, choices=conditions)
    starting_price = models.FloatField(default=0.0)
    last_bid = models.FloatField(default=0.0)
    end_date = models.DateTimeField()
    picture1 = models.ImageField(default="placeholder.png")
    picture2 = models.ImageField(default="placeholder.png", null=True, blank=True)
    picture3 = models.ImageField(default="placeholder.png", null=True, blank=True)
    picture4 = models.ImageField(default="placeholder.png", null=True, blank=True)
    picture5 = models.ImageField(default="placeholder.png", null=True, blank=True)
    picture6 = models.ImageField(default="placeholder.png", null=True, blank=True)
    phone_number = PhoneNumberField()
    currency = models.CharField(max_length=20, choices=currencies)
    location = PlacesField(null=True)
    finished_email_sent = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.title
    
    def get_date_from_datetime(self) -> str:
      return self.end_date.strftime("%Y-%m-%d")
    
    def get_hour_from_datetime(self) -> str:
      return self.end_date.strftime("%I:%M %p")
    
    def get_date(self) -> str:
      return self.end_date.strftime("%d %B %Y at %I:%M %p")
    
    def get_end_date_translated(self) -> str:
      month_no = int(self.end_date.strftime("%m"))
      return self.end_date.strftime("%d " + _(calendar.month_name[month_no]) + " %Y " + _("at") + " %I:%M %p")
    
    def get_date_posted_translated(self) -> str:
      month_no = int(self.date_posted.strftime("%m"))
      return self.date_posted.strftime("%d " + _(calendar.month_name[month_no]) + " %Y, " + " %I:%M %p")
    
    def get_date_posted_string(self) -> str:
      return self.date_posted.strftime("%d %B %Y, %I:%M %p")
    
    def get_seller(self):
      return self.seller

    def get_detail_url(self):
      return reverse('detail-product', kwargs={'pk' : self.pk})
    
    def get_delete_url(self):
    	return reverse('delete-product', kwargs={'pk' : self.pk})
    
    def get_end_date_ISO_formatted(self):
      return self.end_date.strftime("%d %B %Y %H:%M")
    
    def get_time_remaining(self):
      return ("%d days, %d hrs, %d mins" % dhms_from_seconds(date_diff_in_seconds(self.end_date, datetime.now(timezone.utc) + timedelta(hours = 3))))

products/forms.py
import datetime
from multiprocessing import Condition

from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.forms.models import ModelForm
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.formfields import PhoneNumberField
from places.fields import PlacesField
from users.models import Account

from .models import Product

currencies = [
            ('1', _('LEI')),
            ('2', _('USD (US$)')),
            ('3', _('EUR (€)')),
            ('4', _('GBP (£)'))
        ]

conditions = [   
            ('1', _('New')),
            ('2', _('Used'))
        ]


class ProductForm(ModelForm):
    title = forms.CharField(label=_('Title'), max_length=100, help_text=_('Please set a suggestive title for your product which contains at least 5 characters'))
    description = forms.CharField(widget=forms.Textarea, max_length=3000, help_text=_('Please describe the product you are selling'), label=_('Description'))
    condition =  forms.ChoiceField(choices=conditions, label=_('Condition'))
    starting_price = forms.FloatField(localize=True, label=_('Starting price'), help_text=_('Please set the product\'s starting price'))
    end_date = forms.DateField()
    end_hour = forms.TimeField(input_formats = ['%I:%M %p'], widget=forms.TimeInput(), help_text=_('Please choose an ending date and time for the bidding'), label=_("End hour"))
    picture1 = forms.ImageField(label=_('Main image'), help_text=_('Please set a main image for your product'))
    picture2 = forms.ImageField(label=_('Image 2'), required=False)
    picture3 = forms.ImageField(label=_('Image 3'), required=False)
    picture4 = forms.ImageField(label=_('Image 4'), required=False)
    picture5 = forms.ImageField(label=_('Image 5'), required=False)
    picture6 = forms.ImageField(label=_('Image 6'), required=False)
    delete1 = forms.BooleanField(required=False)
    delete2 = forms.BooleanField(required=False)
    delete3 = forms.BooleanField(required=False)
    delete4 = forms.BooleanField(required=False)
    delete5 = forms.BooleanField(required=False)
    delete6 = forms.BooleanField(required=False)
    currency = forms.ChoiceField(choices=currencies, label=_('Currency'))
    phone_number = PhoneNumberField(widget=forms.TextInput(), label=_("Phone number"), help_text=_('Please enter a phone number (e.g. +40792011221).'))
    phone_number.error_messages['invalid'] = _('Enter a valid phone number (e.g. +40792011221).')
    location = PlacesField()

    class Meta:
        model = Product
        fields = ["title", "description", "condition", "end_date", "end_hour", "picture1",
                  "picture2", "picture3", "picture4", "picture5", "picture6", "delete6", 
                  "delete2", "delete3", "delete4", "delete5", "phone_number", "currency",
                  "location"]

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if len(title) < 5:
            raise ValidationError(_("The title should contain at least 5 characters."))
        return title
    
    def clean_description(self):
        description = self.cleaned_data.get('description')
        if len(description) < 5:
            raise ValidationError(_("The description should contain at least 5 characters."))
        return description
    
    def clean_starting_price(self):
        starting_price = self.cleaned_data.get('starting_price')
        if starting_price < 0:
            raise ValidationError(_("The starting price should be greater than or equal to 0."))
        return starting_price
    
    def clean_end_hour(self):
        end_date = self.cleaned_data.get('end_date')
        end_hour = self.cleaned_data.get('end_hour')
        current_datetime = datetime.datetime.combine(end_date, end_hour)
        if current_datetime < datetime.datetime.now():
            raise ValidationError(_("The date and time cannot be in the past."))
        return end_hour
    
    
class SearchForm(forms.Form):
    conditions2 = [   
            ('0', _('Choose condition...')),
            ('1', _('New')),
            ('2', _('Used'))
        ]
    seller_id_list = Product.objects.values('seller').distinct('seller')
    sellers = [('0', _('Choose seller...'))]
    for seller_id in seller_id_list:
        id = seller_id['seller']
        sellers.append((id, Account.objects.get(pk=id)))
        
    location_places_list = Product.objects.values('location').distinct('location')
    locations = []
    for nr, location_place in enumerate(location_places_list):
       locations.append((nr + 1, location_place['location'].place))
    locations.sort(key=lambda x:x[1])
    search_term = forms.CharField(required=False, label=_('Search term...'))
    seller = forms.ChoiceField(choices=sellers, label=_('Seller'), required=False)
    condition =  forms.ChoiceField(choices=conditions2, label=_('Condition'), required=False)
    starting_price = forms.FloatField(widget=forms.NumberInput, localize=True, label=_('Starting price should be less than...'), required=False, validators=[MinValueValidator(1)])
    end_date = forms.DateField(label=_('The auction should end no later than...'), required=False)
    location = forms.MultipleChoiceField(choices=locations, label=_('Choose the city, e.g. Bucuresti, Romania'), required=False)

bidnbuy/views.py
import datetime
from tabnanny import verbose
from timeit import repeat
import favourites
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render
from products.models import Product

from favourites.models import Favourite
from products.forms import SearchForm
from django.contrib.postgres.search import SearchVector
from django.utils.translation import gettext as _
from django.db.models import Q
from users.models import Account
from itertools import chain
from .utils import filter_products
from .tasks import send_email_task
from background_task.models import Task
# Create your views here.

sellers = [      
            ('1', _('New')),
            ('2', _('Used'))
        ]

@login_required(login_url='login')
def homePage(request):
    if len(Task.objects.filter(verbose_name="send_email_task")) == 0:
        send_email_task(repeat=60, verbose_name="send_email_task")
    if request.method == 'GET':
        searchForm = SearchForm()
        products = Product.objects.all()
    else:
        searchForm = SearchForm(request.POST)
        if searchForm.is_valid():
            cd = searchForm.cleaned_data
            products = Product.objects.all()
            products = filter_products(cd, products)
        else:
            products = Product.objects.all()
    if len(products):
        products = products.filter(end_date__gt=datetime.datetime.now().date()).order_by("end_date")
    paginator = Paginator(products, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    user = request.user
    favourites_list = []
    for product in page_obj:
        if len(Favourite.objects.filter(user=user, product=product)):
            favourites_list.append(product)
    if len(Product.objects.all()) == 0:
        msg = _('There are no ads available at the moment...')
        if len(products) == 0:
            msg = _('There are no products matching your search...')
    else:
        msg = _('There are no products matching your search...')
        
    return render(request, 'home.html', {'page_obj': page_obj,
                            'range': range(1, page_obj.paginator.num_pages + 1),
                            'favourites_list' : favourites_list,
                            'title': _('Available products'),
                            'no_items_msg': msg,
                            'page_title': _('Home'),
                            'searchForm': searchForm,
                            })

bidnbuy/templates/products/new_product.html
{% extends 'base.html' %}
{% load i18n %}
{% load materializecss %}
{% block title %}{% trans 'New Product' %}{% endblock title %}
{% block content %}
<head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
        var addPicture = function(id, url) {
            var img_zone = $("#preview-pictures-zone");
            var preview_img = '<div class="preview-image preview-show-' + id + '">';
                            
            if (id != "1") {
                preview_img += '<div class="image-cancel" data-no="'+ id + '" onclick="loadPlaceholder(' + id + ')"><label class="waves-effect light btn-small text-uppercase btn-outline red" style="width: 90%">{% trans "Delete" %}</label></div>';
            }
        
            preview_img += '<div class="image-zone"><img id="picture' + id + '" src="'+ url +'"></div>' +
                        '<div class="tools-edit-image">' +
                        '<label for="id_picture' + id + '" class="waves-effect light btn-small text-uppercase btn-outline" style="width: 90%">{% trans "Upload" %}</label>' +
                        '<input type="file" name="picture' + id + '" accept="image/*" id="id_picture'+ id + '"  onchange="loadFile(event, ' + id + ')"></input>' +
                        "</div>" +
                        "</div>";
            
            img_zone.append(preview_img);
        }
    </script>
    <script src="{% static 'app.js' %}"></script>
    <style>
        input[type="file"] {
            display: none;
        }
        .help-block{
            color: #ff0000 !important;
        }
        .errorlist {
            color: red;
        }
    </style>
</head>
<div class="container">
    <div layout:fragment="content">
        <div class="justify-content-center h-100">
            <div class="d-flex justify-content-center">
                    <h1 id="form-title">{% trans "New product" %}</h1>
            </div>
            {% for non_field_error in form.non_field_errors %}
                <script>
                    showErrorMessage("{{non_field_error}}");
                </script>
            {% endfor %}
            <form enctype='multipart/form-data' class="justify-content-center" method="POST" style="width: 100%;">
                    {% csrf_token %}
                    <div class="d-flex justify-content-center product_card">
                        <h3 style="margin-left: 5%;"> {% trans "Product details" %} </h3>
                        <div class="justify-content-center form_content">
                            <div class="input-group mb-3">
                                {{form.title|materializecss:'icon=title'}}<br>
                            </div>
                            <div class="input-group mb-3">
                                {{form.condition|materializecss:'icon=chevron_right'}}<br>
                            </div>
                            <div class="input-group mb-3">
                                {{form.description|materializecss:'icon=description'}}<br>
                            </div>
                            <div class="input-group mb-3">
                                <div style="display: inline;">
                                    {{form.starting_price|materializecss:'icon=attach_money'}}<br>
                                </div>
                                <div style="display: inline;">
                                    {{form.currency|materializecss}}<br>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-center product_card">
                        <h3 style="margin-left: 5%;"> {% trans "Images" %} </h3>
                        <div class="justify-content-center form_content">
                            <p class="p_content"><i class="small material-icons">image</i> {% trans 'Please choose some images which describe your product' %} </p>
                        <p> {% trans 'The first image will be the main image of your product' %} </p>
                        <p style="font-style: italic"> {% trans 'We recommend using horizontal/landscape images' %} </p>
                        {{form.errors.picture1}}
                        {{form.errors.picture2}}
                        {{form.errors.picture3}}
                        {{form.errors.picture4}}
                        {{form.errors.picture5}}
                        {{form.errors.picture6}}
                        <div class="preview-images-zone" id="preview-pictures-zone">
                            {% if object.picture1 %}
                                <script>
                                    addPicture("1", "{{object.picture1.url}}");
                                </script>
                            {% else %}
                                <script>
                                    addPicture("1", "{% static 'media/placeholder.png' %}");
                                </script>
                            {% endif %}
                            {% if object.picture2 %}
                                <script>
                                    addPicture("2", "{{object.picture2.url}}");
                                </script>
                            {% else %}
                                <script>
                                    addPicture("2","{% static 'media/placeholder.png' %}");
                                </script>
                            {% endif %}
                            {% if object.picture3 %}
                                <script>
                                    addPicture("3", "{{object.picture3.url}}");
                                </script>
                            {% else %}
                                <script>
                                    addPicture("3", "{% static 'media/placeholder.png' %}");
                                </script>
                            {% endif %}
                            {% if object.picture4 %}
                                <script>
                                    addPicture("4", "{{object.picture4.url}}");
                                </script>
                            {% else %}
                                <script>
                                    addPicture("4", "{% static 'media/placeholder.png' %}");
                                </script>
                            {% endif %}
                            {% if object.picture5 %}
                                <script>
                                    addPicture("5", "{{object.picture5.url}}");
                                </script>
                            {% else %}
                                <script>
                                    addPicture("5", "{% static 'media/placeholder.png' %}");
                                </script>
                            {% endif %}
                            {% if object.picture6 %}
                                <script>
                                    addPicture("6", "{{object.picture6.url}}");
                                </script>
                            {% else %}
                                <script>
                                    addPicture("6", "{% static 'media/placeholder.png' %}");
                                </script>
                            {% endif %}              
                        </div>
                        </div>
                    </div>    
                    <div class="d-flex justify-content-center product_card">
                        <h3 style="margin-left: 5%;"> {% trans "Auction details" %} </h3>
                        <div class="justify-content-center form_content">
                            <div class="input-group mb-3">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">perm_contact_calendar</i>
                                <input type="text" name="end_date" class="validate invalidate datepicker" required id="id_end_date" placeholder="yyyy-mm-dd"></input>
                                <label class for="id_end_date">{% trans 'End date' %}</label>
                            </div>
                            </div>
                            <div class="input-group mb-3">
                                {{form.end_hour|materializecss:'icon=access_time'}}<br>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-center product_card">
                        <h3 style="margin-left: 5%;"> {% trans "Contact details" %} </h3>
                        <div class="justify-content-center form_content">
                            <div class="input-group mb-3">
                                {{form.phone_number|materializecss:'icon=phone'}}
                            </div>
                            <h4><i class="small material-icons prefix">location_on</i>{% trans "Location" %}</h4>
                            {{form.location}}
                            <div class="d-flex justify-content-center mt-4 login_container">
                                <button type='submit' class="waves-effect light btn-large btn-block text-uppercase btn-outline">{% trans "Submit" %}</button>
                            </div>
                            {{form.media}}
                        </div>
                    </div>
            </form>           
        </div>
    </div>
</div>
{% block script %}
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        var loadFile = function(event, no) {
            var output = document.getElementById('picture' + no);
            output.src = URL.createObjectURL(event.target.files[0]);
            $('#id_delete_' + no).prop('checked', false);
            output.onload = function() {
                URL.revokeObjectURL(output.src) // free memory
            }
        };
        var loadPlaceholder = function(no) {
            var output = document.getElementById('picture' + no);
            output.src = "{% static 'media/placeholder.png' %}";
            $('#id_delete' + no).prop('checked', true);
            output.onload = function() {
            URL.revokeObjectURL(output.src) // free memory
            }
        };

        const bullet = "\u2022";
        const bulletWithSpace = `${bullet} `;
        const enter = 13;


        const handleInput = (event) => {
        const { keyCode, target } = event;
        const { selectionStart, value } = target;

        if (keyCode === enter) {
            target.value = [...value]
            .map((c, i) => i === selectionStart - 1
                ? `\n${bulletWithSpace}`
                : c
            )
            .join('');
            
            target.selectionStart = selectionStart+bulletWithSpace.length;
            target.selectionEnd = selectionStart+bulletWithSpace.length;
        }

        if (value[0] !== bullet) {
            target.value = `${bulletWithSpace}${value}`;
        }
        }
        $(document).ready(function(){
            $("input#id_end_hour").attr({
                "class" : "timepicker",
            });
            $("input#id_end_date").attr({
                "class" : "datepicker",
            });
            // Initialize materialize data picker
            $('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
            $('.timepicker').timepicker({'format': 'hh:mm'});
            


            $('select').formSelect();
            $("textarea#id_description").attr({
                "data-length" : "3000",
                "onkeyup": "handleInput(event)",
            });
            $("#id_location_0").attr({
                "placeholder" : "{% trans "Enter your city or postal code..."%}",
            });
            $("input#id_title").attr({
                "data-length" : "100",
            });
            $('input#id_title, textarea#id_description').characterCounter();
            $('.modal').modal();
        });
        $(function(){
            var dtToday = new Date();
            $('.datepicker').datepicker({minDate: dtToday,
                                        format: 'yyyy-mm-dd'});
        });
    </script> 
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
</script>
{% endblock script %}
{% endblock content %}